main:
  - name: Research
    url: "/#research"
    weight: 10
  - name: Publications
    url: "/#publications"
    weight: 20
  - name: Experience
    pageRef: "/experience"
    weight: 30
  - name: Projects
    pageRef: "/projects"
    weight: 40
